Computer-Communications-Project/Computer-Communications-Project/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Computer_Communications_Project.Models
{
    public class User
    {
        [Required]
        [Key]
        public string UserName { set; get; }
        [Required]
        public string Password { set; get; }
    }
}

Computer-Communications-Project/Computer-Communications-Project/Controllers/HallController.cs
using Computer_Communications_Project.DAL;
using Computer_Communications_Project.Models;
using Computer_Communications_Project.ViewModel;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Computer_Communications_Project.Controllers
{
    public class HallController : Controller
    {
        // GET: Hall
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult EditHall()
        {
            HallViewModel hvm = new HallViewModel();
            HallsDal dal = new HallsDal();
            hvm.Halls = dal.Halls.ToList<Hall>();
            return View("ShowDetails", hvm);
        }
        public ActionResult ShowDetails(string hallName)
        {
            HallsDal dal = new HallsDal();
            HallViewModel hvm = new HallViewModel();
            hvm.Hall = dal.Halls.Find(hallName);
            hvm.Halls = dal.Halls.ToList<Hall>();
            //Hall editHall = dal.Halls.Find(hallName);
            if (Request.Form["HallName"] == null)
            {
                return RedirectToAction("MyPage", "Home");
            }
            return View(hvm);
        }
        public ActionResult Edit(Hall hall)
        {
            HallsDal dal = new HallsDal();
            Hall objHall = (from x in dal.Halls
                              where x.HallName == hall.HallName
                              select x).Single<Hall>();
            dal.Halls.Remove(objHall);
            dal.Halls.Add(hall);
            dal.SaveChanges();
            return RedirectToAction("MyPage", "Home");
        }
    }
}

Computer-Communications-Project/Computer-Communications-Project/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Computer_Communications_Project.DAL;
using Computer_Communications_Project.Models;
using Computer_Communications_Project.ViewModel;

namespace Computer_Communications_Project.Controllers
{
    public class MovieController : Controller
    {
        // GET: Movie
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Movie()
        {
            return View();
        }

        public ActionResult ManageMovie()
        {
            MoviesDal dal = new MoviesDal();
            MovieViewModel mvm = new MovieViewModel();
            List<Movie> movies = dal.Movies.ToList<Movie>();
            mvm.movieName = new Movie();
            mvm.Movies = movies;
            return View("SearchMovie", mvm);
        }

        public ActionResult SearchMovie()
        {
            MoviesDal dal = new MoviesDal();
            MovieViewModel mvm = new MovieViewModel();
            if (Request.Form["MovieName"] == null)
            {
                return RedirectToAction("MyPage", "Home");
            }
            string searchVal = Request.Form["MovieName"].ToString();
            List<Movie> objMovies = (from x in dal.Movies
                                   where x.MovieName.Contains(searchVal)
                                   select x).ToList<Movie>();
            Movie objMovie = new Movie();
            objMovie.MovieName = searchVal;
            mvm.movieName = objMovie;
            mvm.Movies = objMovies;
            return View(mvm);
        }

        [HttpGet]
        public ActionResult AddMovie()
        {
            return View("AddMovie");
        }

        [HttpPost]
        public ActionResult AddMovie(Movie movie)
        {
            MoviesDal dal = new MoviesDal();
            HallsDal hallDal = new HallsDal();
            Hall hall = new Hall();
            var sameHallname = dal.Movies.Any(x => x.Date == movie.Date && x.HallName == movie.HallName);
            var HallName = hallDal.Halls.Any(x => x.HallName == movie.HallName);
            var sameDate = dal.Movies.Any(x => x.Date == movie.Date);
            if (ModelState.IsValid)
            {
                if (sameDate == true)
                {
                    if(sameHallname == true)
                    {
                        TempData["MovieStatus"] = "There is a movie at the same date and hall.";
                        return RedirectToAction("AddMovie",movie);
                    }
                    else
                    {
                        if(HallName == false)
                        {
                            hall.HallName = movie.HallName;
                            hall.ColNumber = 10;
                            hall.RowNumber = 10;
                            hallDal.Halls.Add(hall);
                            hallDal.SaveChanges();
                        }
                        dal.Movies.Add(movie);
                        dal.SaveChanges();
                        
                    }
                }
                else
                {
                    if (HallName == false)
                    {
                        hall.HallName = movie.HallName;
                        hall.ColNumber = 10;
                        hall.RowNumber = 10;
                        hallDal.Halls.Add(hall);
                        hallDal.SaveChanges();
                    }
                    dal.Movies.Add(movie);
                    dal.SaveChanges();
                }
                return RedirectToAction("MyPage", "Home");
            }
            return View("AddMovie", movie);
        }
        public ActionResult Delete(string movieName)
        {
            MoviesDal dal = new MoviesDal();
            Movie objMovie = new Movie();
            if (movieName != "")
            {
                objMovie = (from x in dal.Movies
                            where x.MovieName == movieName
                            select x).Single<Movie>();
            }
            else
            {
                return RedirectToAction("MyPage", "Home");
            }
            dal.Movies.Remove(objMovie);
            dal.SaveChanges();
            return RedirectToAction("MyPage", "Home");
        }
        public ActionResult EditMovie()
        {
            MovieViewModel mvm = new MovieViewModel();
            MoviesDal dal = new MoviesDal();
            mvm.Movies = dal.Movies.ToList<Movie>();
            return View("ShowDetails", mvm);
        }
        public ActionResult ShowDetails(string movieName)
        {
            MoviesDal dal = new MoviesDal();
            MovieViewModel mvm = new MovieViewModel();
            mvm.movieName = dal.Movies.Find(movieName);
            mvm.Movies = dal.Movies.ToList<Movie>();
            //Movie editMovie = dal.Movies.Find(movieName);
            if (Request.Form["MovieName"] == null)
            {
                return RedirectToAction("MyPage", "Home");
            }
            return View(mvm);
        }
        public ActionResult Edit(MovieViewModel movie)
        {
            MoviesDal dal = new MoviesDal();
            HallsDal hallDal = new HallsDal();
            Hall hall = new Hall();
            var HallName = hallDal.Halls.Any(x => x.HallName == movie.movieName.HallName);
            Movie objMovie = (from x in dal.Movies
                        where x.MovieName == movie.movieName.MovieName
                        select x).Single<Movie>();
            if (HallName == false)
            {
                hall.HallName = movie.movieName.HallName;
                hall.ColNumber = 10;
                hall.RowNumber = 10;
                hallDal.Halls.Add(hall);
                hallDal.SaveChanges();
            }
            dal.Movies.Remove(objMovie);
            dal.Movies.Add(movie.movieName);
            dal.SaveChanges();
            return RedirectToAction("EditMovie");
        }
    }
}

Computer-Communications-Project/Computer-Communications-Project/Controllers/UserController.cs
using Computer_Communications_Project.Classes;
using Computer_Communications_Project.DAL;
using Computer_Communications_Project.Models;
using Computer_Communications_Project.ViewModel;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;

namespace Computer_Communications_Project.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Register()
        {
            if (Session["userType"] != null)
            {
                return RedirectToAction("MyPage", "Home");
            }
            return View(new User());
        }
        public ActionResult SubmitRegister(User user)
        {
            Encryption enc = new Encryption();
            UsersDal dal = new UsersDal();
            if (ModelState.IsValid)
            {
                var isUserAlreadyExists = dal.Users.Any(x => x.UserName == user.UserName);
                string hashedPassword = enc.CreateHash(user.Password);
                if (isUserAlreadyExists)
                {
                    TempData["LoginStatus"] = "Username already exists.";
                    return View("Register", user);
                }
                user.Password = hashedPassword;
                dal.Users.Add(user);
                dal.SaveChanges();
                TempData["LoginStatus"] = null;
                return RedirectToAction("MyPage", "Home");
            }
            return View("Register", user);
        }
        public ActionResult UserLogin()
        {
            if (Session["loggedOn"] == null)
            {
                Session["LogoutStatus"] = null;
                return View(new User());
            }
            return RedirectToAction("MyPage", "Home");
        }

        public ActionResult AdminLogin()
        {
            if (Session["loggedOn"] == null)
            {
                Session["LogoutStatus"] = null;
                return View(new Admin());
            }
            return RedirectToAction("Logout", "User");
        }

        public ActionResult Logout()
        {
            if (Session["loggedOn"] == null)
            {
                Session["LogoutStatus"] = "No user is logged on.";
            }
            return View();
        }
        public ActionResult LogoutAction()
        {
            Session["username"] = null;
            Session["loggedOn"] = null;
            Session["LogoutStatus"] = null;
            Session["userType"] = null;
            return RedirectToAction("MyPage", "Home");
        }

        public ActionResult SubmitLogin(User user)
        {
            UsersDal dal = new UsersDal();
            List<User> users = dal.Users.ToList<User>();
            Encryption enc = new Encryption();
            bool exists = false;
            foreach (User u in users)
            {
                if (u.UserName == user.UserName && enc.ValidatePassword(user.Password, u.Password))
                {
                    exists = true;
                    break;
                }
            }
            if (exists == true)
            {
                FormsAuthentication.SetAuthCookie("cookie", true);
                Session["username"] = user.UserName;
                Session["loggedOn"] = "true";
                TempData["LoginStatus"] = null;
                Session["userType"] = "user";
                return RedirectToAction("MyPage", "Home");
            }
            else
            {
                TempData["LoginStatus"] = "Username or Password are incorrect.";
                return View("SubmitLogin", user);
            }
        }

        public ActionResult SubmitAdminLogin(Admin user)
        {
            AdminsDal dal = new AdminsDal();
            List<Admin> users = dal.Users.ToList<Admin>();
            Encryption enc = new Encryption();
            bool exists = false;
            foreach (Admin u in users)
                if (u.UserName == user.UserName && enc.ValidatePassword(user.Password, u.Password))
                {
                    exists = true;
                    break;
                }
            if (exists == true)
            {
                FormsAuthentication.SetAuthCookie("cookie", true);
                Session["username"] = user.UserName;
                Session["loggedOn"] = "true";
                Session["userType"] = "admin";
                TempData["LoginStatus"] = null;
                return RedirectToAction("MyPage", "Home");
            }
            else
            {
                TempData["LoginStatus"] = "Username or Password are incorrect.";
                return View("AdminLogin", user);
            }
        }
        public ActionResult AdminTools()
        {
            if (Session["userType"] == null || Session["userType"].ToString() != "admin")
            {
                return RedirectToAction("MyPage", "Home");
            }
            return View();
        }
        public ActionResult ManageUsers()
        {
            UserViewModel uvm = new UserViewModel();
            uvm.user = new User();
            uvm.users = new List<User>();
            return View("SearchUser", uvm);
        }

        public ActionResult SearchUser()
        {
            UsersDal dal = new UsersDal();
            UserViewModel uvm = new UserViewModel();
            if (Request.Form["UserName"] == null)
            {
                return RedirectToAction("MyPage", "Home");
            }
            string searchVal = Request.Form["UserName"].ToString();
            List<User> objUsers = (from x in dal.Users
                                   where x.UserName.Contains(searchVal)
                                   select x).ToList<User>();
            User objUser = new User();
            objUser.UserName = searchVal;
            uvm.user = objUser;
            uvm.users = objUsers;
            return View(uvm);
        }
        public ActionResult AddAdmin()
        {
            if (Session["userType"] != null && Session["userType"].ToString() == "admin")
            {
                return View(new Admin());
            }
            return RedirectToAction("MyPage", "Home");
        }

        public ActionResult SubmitAdminRegister(Admin admin)
        {
            AdminsDal dal = new AdminsDal();
            Encryption enc = new Encryption();
            if (ModelState.IsValid)
            {
                var isUserAlreadyExists = dal.Users.Any(x => x.UserName == admin.UserName);
                string hashedPassword = enc.CreateHash(admin.Password);
                if (isUserAlreadyExists)
                {
                    TempData["LoginStatus"] = "Username already exists.";
                    return View("AddAdmin", admin);
                }
                admin.Password = hashedPassword;
                dal.Users.Add(admin);
                dal.SaveChanges();
                TempData["LoginStatus"] = null;
                return RedirectToAction("MyPage", "Home");
            }
            return View("AddAdmin", admin);
        }
    }
}

Computer-Communications-Project/Computer-Communications-Project/Views/User/AddAdmin.cshtml
@model Computer_Communications_Project.Models.Admin
@using Computer_Communications_Project.Models
@{
    ViewBag.Title = "Add admin";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

</head>
<body>
    <h2>@ViewBag.Title</h2>
    <br />
    <div>
        @using (Html.BeginForm("SubmitAdminRegister", "User", FormMethod.Post))
        {
            <table>
                <tr>
                    <td>Username: </td>
                    <td>@Html.TextBoxFor(m => m.UserName) @Html.ValidationMessageFor(x => x.UserName) </td>
                </tr>
                <tr>
                    <td>Password: </td>
                    <td>@Html.PasswordFor(m => m.Password) @Html.ValidationMessageFor(x => x.Password)</td>
                </tr>
            </table>
            <br />
            <h4 style="color:red">@TempData["LoginStatus"]</h4>
            <br />
            <br />
            <input id="SubmitAdminRegister" type="Submit" value="Add Admin" />
            <br />
        }
    </div>
</body>
</html>

Computer-Communications-Project/Computer-Communications-Project/Views/User/AdminLogin.cshtml
@model Computer_Communications_Project.Models.Admin

@using Computer_Communications_Project.Models
@{
    ViewBag.Title = "Admin Login";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Admin Login</title>

    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

</head>
<body>
    <h2>Administrator Login</h2>
    <br />
    <div>
        @using (Html.BeginForm("SubmitAdminLogin", "User", FormMethod.Post))
        {
            <table>
                <tr>
                    <td>Username: </td>
                    <td>@Html.TextBoxFor(m => m.UserName)</td>
                </tr>
                <tr>
                    <td>Password: </td>
                    <td>@Html.PasswordFor(m => m.Password)</td>
                </tr>
            </table>
            <br />
            <h4 style="color:red">@TempData["LoginStatus"]</h4>
            <br />
            <input id="SubmitAdminLogin" type="submit" value="Login" />
        }
    </div>
</body>
</html>

Computer-Communications-Project/Computer-Communications-Project/Views/User/AdminTools.cshtml
@{
    ViewBag.Title = "AdminTools";
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Admin Tools</title>

    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

</head>
<body>
    <h1><strong>Administrator Tools</strong></h1>
    <br /><br />
    <div>
        @using (Html.BeginForm("SubmitAdminLogin", "User", FormMethod.Post))
        {
            <h2>
                <strong>
                    To manage list of users, click <button type="button" onclick="location.href='@Url.Action("ManageUsers", "User")'"> Search User </button>
                    <br /><br />
                    To manage list of movies, click <button type="button" onclick="location.href='@Url.Action("ManageMovie", "Movie")'"> Search Movie </button>
                    <br /><br />
                    To add an administrator user, click <button type="button" onclick="location.href='@Url.Action("AddAdmin","User")'">Add Admin</button>
                    <br /><br />
                    To add a moives, click <button type="button" onclick="location.href='@Url.Action("AddMovie","Movie")'">Add Movie</button>
                    <br /><br />
                    To edit a moives, click <button type="button" onclick="location.href='@Url.Action("EditMovie","Movie")'">Edit Movie</button>
                    <br /><br />
                    To edit a hall, click <button type="button" onclick="location.href='@Url.Action("EditHall","Hall")'">Edit Hall</button>
                    <br /><br />
                </strong>
            </h2>
        }
        <br /><br /><br /><br /><br />
    </div>
</body>
</html>

Computer-Communications-Project/Computer-Communications-Project/Views/User/Logout.cshtml
@{
    ViewBag.Title = "Logout";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Log out</title>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

</head>
<body>
    <h2>Log out</h2>
    <br />
    <div>
        <h3 style="color:red">@Session["LogoutStatus"]</h3>
        <br />
        @if (Session["loggedOn"] != null)
        {
            using (Html.BeginForm("LogoutAction", "User", FormMethod.Post))
            {
                <input id="LogoutAction" type="submit" value="Log out" />
            }
        }
    </div>
</body>
</html>

Computer-Communications-Project/Computer-Communications-Project/Views/User/Register.cshtml
@model Computer_Communications_Project.Models.User
@using Computer_Communications_Project.Models
@{
    ViewBag.Title = "Register";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Register</title>

    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

</head>
<body>
    <h2>Register</h2>
    <br />
    <div>
        @using (Html.BeginForm("SubmitRegister", "User", FormMethod.Post))
        {
            <table>
                <tr>
                    <td>Username: </td>
                    <td>@Html.TextBoxFor(m => m.UserName)</td>
                </tr>
                <tr>
                    <td>Password: </td>
                    <td>@Html.PasswordFor(m => m.Password)</td>
                </tr>
            </table>
            <br />
            <h4 style="color:red">@TempData["LoginStatus"]</h4>
            <br />
            <input id="SubmitRegister" type="Submit" value="Register" />
        }
    </div>
</body>
</html>

Computer-Communications-Project/Computer-Communications-Project/Views/User/SearchUser.cshtml
@model Computer_Communications_Project.ViewModel.UserViewModel

@using Computer_Communications_Project.Models;
@{
    ViewBag.Title = "SearchUser";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Search User</title>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 13pt;
        }

        .Grid {
            border: 1px solid #ccc;
            border-collapse: collapse;
        }

            .Grid th {
                background-color: #F7F7F7;
                font-weight: bold;
            }

            .Grid th, .Grid td {
                padding: 5px;
                border: 1px solid #ccc;
            }

            .Grid, .Grid table td {
                border: 0px solid #ccc;
            }

                .Grid th a, .Grid th a:visited {
                    color: #333;
                }
    </style>
</head>
<body>
    <div>
        <form action="SearchUser" method="post">
            <br />
            <table>
                <tr>
                    <td>Enter Username to search:</td>
                    <td><input id="Text" type="text" name="username" value="@Model.user.UserName" /></td>
                </tr>
                <tr>
                    <td><input id="Submit" type="submit" value="Search User" /></td>
                </tr>
            </table>
        </form>
    </div>
    <br />
    <b>Search Results:</b>
    <br />
    <div>
        @{
            WebGrid obj = new WebGrid(Model.users, canPage: false, canSort: false);
        }
        @obj.GetHtml(htmlAttributes: new { @id = "WebGrid", @class = "Grid" },
        columns: obj.Columns(
                 obj.Column("Username", "Username"),
                 obj.Column("Password", "Password")))
    </div>

</body>
</html>

Computer-Communications-Project/Computer-Communications-Project/Views/User/UserLogin.cshtml
@model Computer_Communications_Project.Models.User
@using Computer_Communications_Project.Models
@{
    ViewBag.Title = "User Login";
}

<script src="~/Scripts/jquery-3.3.1.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>User Login</title>

</head>
<body>
    <h2>Login</h2>
    <br />
    <div>
        @using (Html.BeginForm("SubmitLogin", "User", FormMethod.Post))
        {
            <table>
                <tr>
                    <td>Username: </td>
                    <td> @Html.TextBoxFor(m => m.UserName)</td>
                    <td>@Html.ValidationMessageFor(x => x.UserName)</td>
                </tr>
                <tr>
                    <td>Password: </td>
                    <td> @Html.PasswordFor(m => m.Password)</td>
                    <td>@Html.ValidationMessageFor(x => x.Password)</td>
                </tr>
            </table>
            <br />
            <h4 style="color:red">@TempData["LoginStatus"]</h4>
            <br />
            <input id="SubmitLogin" type="submit" value="Login" />
        }
    </div>
</body>
</html>